### ISSUE TITLE
rake-imported files missing some countries

### ISSUE THREAD

**Issue by dandyn** [mlitwiniuk/localized_country_select#25]
I'm using the latest version of the gem (0.9.9) and some countries are missing from the imported files such as Australia and Argentina while they still appear in http://www.unicode.org/cldr/charts/latest/summary/en.html

**Comment by mlitwiniuk** [comment]
Should be fixed now, please check version 0.9.10

**Comment by dandyn** [comment]
Thanks for your time.
Unfortunately, I still see incoherences in the files (mostly languages):
- `:AR => "Western Armenian"` instead of Argentina
- Some items that are not countries are added as well, such as FONXSAMP, ITIHASA and LUNA1918
- Those items replace existing countries, for example `:IT => "ITIHASA"` which should be Italy

**Comment by mlitwiniuk** [comment]
Whoa, thanks for that. I've just released hotfix, it's hopefully is ok now.

**Comment by dandyn** [comment]
It works!
Thanks a lot!
